#!/bin/bash


jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git
git config --global user.name "Madison Mehlferber"
git config --global user.email madymehlf@gmail.com
